name: ${name}
version: ${version}
api-version: ${plugin.apiVersion}
author: ${plugin.author}
website: ${plugin.website}
main: ${plugin.main}
depend: [RelluEssentials]

commands:
     base:
          description: Base Command
          usage: